# Generated by Django 4.0.3 on 2022-03-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
